// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYLvCVgapuCRBAGVs5EJf9FdIyOL9w6pE',
    appId: '1:329240607872:web:e7a7209d0b099627a17a65',
    messagingSenderId: '329240607872',
    projectId: 'chefkart-8933c',
    authDomain: 'chefkart-8933c.firebaseapp.com',
    storageBucket: 'chefkart-8933c.firebasestorage.app',
    measurementId: 'G-331WVL9904',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkq-qdKsTkTkbMH-FgO8qCLSE1kME0ZzI',
    appId: '1:329240607872:android:e4dc4ccfcdc81766a17a65',
    messagingSenderId: '329240607872',
    projectId: 'chefkart-8933c',
    storageBucket: 'chefkart-8933c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHHk1Upb7I_aqNwJ9tTdGrAnc59xFYod8',
    appId: '1:329240607872:ios:aad13b03ca16d1cea17a65',
    messagingSenderId: '329240607872',
    projectId: 'chefkart-8933c',
    storageBucket: 'chefkart-8933c.firebasestorage.app',
    iosBundleId: 'com.example.chefKart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHHk1Upb7I_aqNwJ9tTdGrAnc59xFYod8',
    appId: '1:329240607872:ios:aad13b03ca16d1cea17a65',
    messagingSenderId: '329240607872',
    projectId: 'chefkart-8933c',
    storageBucket: 'chefkart-8933c.firebasestorage.app',
    iosBundleId: 'com.example.chefKart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYLvCVgapuCRBAGVs5EJf9FdIyOL9w6pE',
    appId: '1:329240607872:web:3f3284560d6c8deda17a65',
    messagingSenderId: '329240607872',
    projectId: 'chefkart-8933c',
    authDomain: 'chefkart-8933c.firebaseapp.com',
    storageBucket: 'chefkart-8933c.firebasestorage.app',
    measurementId: 'G-4DTCXQMREE',
  );
}
